DELETE http://localhost:4000/api/category/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MTg3NjNiMTY1YzMwNzJhYzZhMWQ5ZiIsImVtYWlsIjoic2ljaGluYXZhaWxpYUBnbWFpbC5jb20ifSwiaWF0IjoxNjc5MzMzMTA3LCJleHAiOjE2NzkzMzY3MDd9.I0R6LNho0Dzj3c6P3nvYSH4rEaDhteKTvm_k9Yfj3A4

{
    "name": "Transports"
}